pipeline {
    agent any
    stages {
        stage('Fetch Git Repository') {
            steps {
                sh "rm -rf mpwa"
                sh "git clone https://github.com/analouro/mpwa.git"
                //
            }
        }
        stage('Setup') {
            steps {
                sh "jenkins/setup.sh"
                //
            }
        }
        stage('Test') {
            steps {
                sh "jenkins/test.sh"
                //
            }
        }
        stage('Build') {
            steps {
                sh "jenkins/build.sh"
                //
            }
        }
        stage('Push') {
            steps {
                sh "jenkins/push.sh"
                //
            }
        }
        stage('Deploy') {
            steps {
                sh "jenkins/deploy.sh"
                //
            }
        }
    }
}