pipeline {
    agent any
    environment{
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
        DATABASE_URI = credentials("DATABASE_URI")
    }
    stages {
        stage('Fetch Git Repository') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh "rm -rf mpwa"
                sh "git clone https://github.com/analouro/mpwa.git"
                //
            }
        }
        stage('Setup') {
            steps {
                sh "jenkins/setup.sh"
                //
            }
        }
        stage('Test') {
            steps {
                sh "jenkins/test.sh"
                //
            }
        }
        stage('Build') {
            steps {
                sh "jenkins/build.sh"
                //
            }
        }
        stage('Push') {
            steps {
                sh "jenkins/push.sh"
                //
            }
        }
        stage('Deploy') {
            steps {
                sh "jenkins/deploy.sh"
                //
            }
        }
    }
}